language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy

sudo: false

before_install:
  - python --version
  - uname -a
  - lsb_release -a
  #Lib unittest2 is needed for some assertRaises tests under Python 2.6
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"

install: pip install -r requirements/testing.txt

script: make coverage

after_success: coveralls

notifications:
  email:
    on_success: never
    on_failure: always
