language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy

sudo: false

install: pip install -r requirements/testing.txt

script: make coverage

after_success: coveralls

notifications:
  email:
    on_success: never
    on_failure: always
